# Generated by Django 5.2.1 on 2025-06-01 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_chapter_status_course_video_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='course_material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=100)),
                ('material', models.FileField(upload_to='materials/')),
                ('status', models.BooleanField(default=False)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='api.chapter')),
            ],
        ),
    ]
