# Generated by Django 5.2.1 on 2025-06-03 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_student_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dept_no',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='dept_no',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
