# Generated by Django 5.2.1 on 2025-06-03 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_cetificate_template'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cetificate_template',
            new_name='Certificate_template',
        ),
    ]
