# Generated by Django 5.2.1 on 2025-06-04 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_student_courses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='assign_courses_student',
        ),
    ]
