# Generated by Django 5.2.1 on 2025-06-05 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_course_category_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='course_textcontent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textcontent', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textcontents', to='api.chapter')),
            ],
        ),
    ]
