# Generated by Django 5.2.1 on 2025-06-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_quiz_answer_quiz_correct_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='background_image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.URLField(),
        ),
    ]
