# Generated by Django 5.2.1 on 2025-06-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_course_background_image_alter_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='background_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
